### ISSUE TITLE
OPTPiX SpriteStudioのアセットデータの著作権について

### ISSUE THREAD

**Issue by polyester-CTRL** [Typhoon0x73/ss6sdk_for_s3d#1]
basic_samplesやchara_boxなどのreadme.txtを読むと、サンプルデータを **組み込んだ** アプリを配布・販売できる一方、それ以外の方法での配布は許可されていないと解釈できると思います。
つまり、このリポジトリでサンプルデータ自体を公開(=配布)することは著作権の面で問題があるのではないでしょうか。

**Comment by Typhoon0x73** [comment]
こちらのプロジェクトではSpriteStudioの導入の検証目的がメインですので以下の文言が該当し、問題がないと認識しております。
`または、OPTPiX SpriteStudio 導入の検証目的でのみご使用いただけます。`

よって、こちらのイシューはクローズします。

**Comment by polyester-CTRL** [comment]
返信ありがとうございます。
> または、OPTPiX SpriteStudio 導入の検証目的でのみご使用いただけます。

この第2項の文には検証目的での「使用」はOKと書いてある一方で、
それ以降の第3項、第4項には検証目的での「配布」はOKとは書かれていません。
また、第5項では前2項で記載した様態以外での再配布が明確に禁止されています。
(恐らく、SpriteStudioの公式サイトを経由せずにサンプルデータだけを使われる状況を回避したいという意図があると思います。アプリに組み込むと、元のデータを取り出せなくなるので。)

このことから、検証目的での使用は許可されているものの、その「使用」にはGitHubリポジトリでの配布が含まれていないと思うのですが、いかがでしょうか？

このプロジェクトで使用することは問題ないものの、このリポジトリにサンプルデータを含めることは問題があるという認識です。
もしサンプルデータを使いたい場合は、SpriteStudioの公式サイトから直接ダウンロードすることが必要だと思います。

**Comment by Typhoon0x73** [comment]
ご確認ありがとうございます。

> それ以降の第3項、第4項には検証目的での「配布」はOKとは書かれていません。

確かに、こちらでは`組み込んだ`としかありませんので、転載・再配布に該当する今回のパターンは不適切である可能性があります。
しかし、
> 前2項で記載した様態以外での再配布が明確に禁止されています。

こちらについて、前２項に記載の態様なので、ファイルの転載・再配布は可能というように判断できます。

ただ、polyester-CTRLさんの記載していただいた意図も理解できるので、今回は
> もしサンプルデータを使いたい場合は、SpriteStudioの公式サイトから直接ダウンロードすることが必要だと思います。

こちらの形で使っていただけるよう修正したいと思います。

**Comment by polyester-CTRL** [comment]
対応ありがとうございます。
既に対応していただいた後で言うのは微妙なのですが、第5項から見た前2項というのは第3項と第4項を指すので、今回のパターンのように組み込んでいないファイルを再配布するのは許可されていないと思います。つまり、ゲームを作ってexeファイルの形で配布はOK、素材であるsseeファイルの配布は禁止ということです。

話が変わりますが、README.txtに従うとSS-Samplesフォルダ内のシェーダーも削除が必要ではないでしょうか？
こちらは更に制限が厳しく、製品版ユーザでないとシェーダーを組み込んだアプリを配布できないようです。
ただし、SS-SamplesのREADME.txtにおける前2項というと第2項も含まれるようにも見えるので、消すかの判断はお任せします。(恐らく表記ミスだと思いますが)

**Comment by polyester-CTRL** [comment]
また、万全を期すならば、gitの履歴から該当ファイルを消すことも必要だと思います。現状では、gitの知識がある人ならば、コミットをたどることで消したファイルを復元できてしまいます。

**Comment by Typhoon0x73** [comment]
> 前2項というのは第3項と第4項を指す

第２項を指すことと、完全に勘違いをしておりました。
違反してますね。

SS-SamplesのほうもLICENSEと相違があった場合にはREADMEが優先されることを見落としておりました。
履歴削除を含む対応を致します。

ご教授感謝します。
